import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/shared/Navbar";
import { PlanProvider } from "@/context/PlanContext";
import { Toaster } from "react-hot-toast";
import Footer from "@/Components/Homepage/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" data-theme="dark" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-[#0b0c0f]">
        <PlanProvider>
          <Navbar />
          {children}
          <Toaster position="bottom-center" />
          <Footer />
        </PlanProvider>
      </body>
    </html>
  );
}